Repository JimNikou/Loopify, pull requests merged in 2024-10, with the labels that each got.

#11 feat/work-in-progress: this commit marks the start of the notification media player, added start/stop capabilities
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/ict/ihu/gr/loopify/ExoPlayerManager.java
  app/src/main/java/ict/ihu/gr/loopify/MainActivity.java
  app/src/main/java/ict/ihu/gr/loopify/MediaPlayerService.java
  app/src/main/res/drawable/music_note.xml
  app/src/main/res/drawable/pause.xml
  app/src/main/res/drawable/play_arrow.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
Labels: issue

#9 docs: added guiding comments for the Cloudfare migration
  .idea/shelf/Uncommitted_changes_before_Checkout_at_11_10_24,_8_30 PM_[Changes]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_11_10_24__8_30PM__Changes_.xml
  app/build.gradle.kts
  app/src/main/java/ict/ihu/gr/loopify/ApiManager.java
  app/src/main/java/ict/ihu/gr/loopify/MainActivity.java
  app/src/main/res/values/strings.xml
Labels: documentation, issue

#14 fix: fixed crash on Android 12+ by adding FLAG_IMMUTABLE to PendingIntent in MediaPlayerService
  app/src/main/java/ict/ihu/gr/loopify/MediaPlayerService.java
Labels: bug, fix

#16 bottom-nav-bar
  app/src/main/java/ict/ihu/gr/loopify/AccountFragment.java
  app/src/main/java/ict/ihu/gr/loopify/MainActivity.java
  app/src/main/java/ict/ihu/gr/loopify/SearchFragment.java
  app/src/main/java/ict/ihu/gr/loopify/YourLibraryFragment.java
  app/src/main/java/ict/ihu/gr/loopify/ui/gallery/NotificationFragment.java
  app/src/main/java/ict/ihu/gr/loopify/ui/gallery/NotificationViewModel.java
  app/src/main/java/ict/ihu/gr/loopify/ui/home/HomeFragment.java
  app/src/main/java/ict/ihu/gr/loopify/ui/slideshow/SettingsFragment.java
  app/src/main/java/ict/ihu/gr/loopify/ui/slideshow/SettingsViewModel.java
  app/src/main/res/drawable/baseline_account_circle_24.xml
  app/src/main/res/drawable/baseline_collections_bookmark_24.xml
  app/src/main/res/drawable/baseline_home_filled_24.xml
  app/src/main/res/drawable/baseline_notifications_24.xml
  app/src/main/res/drawable/baseline_search_24.xml
  app/src/main/res/drawable/baseline_settings_24.xml
  app/src/main/res/drawable/ic_menu_camera.xml
  app/src/main/res/drawable/ic_menu_gallery.xml
  app/src/main/res/drawable/ic_menu_slideshow.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/app_bar_main.xml
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_your_library.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/mobile_navigation.xml
Labels: issue

#24 feat (API endpoint): added more api call functions for providing the UI with all the necessary information
  app/src/main/java/ict/ihu/gr/loopify/ApiManager.java
  app/src/main/java/ict/ihu/gr/loopify/MainActivity.java
Labels: enhancement, issue, backend
